# Default values for elasticsearch.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value
# ======================================
# setup for sub chart external-dns  chart
#
# These are the FQDN for the services we need.  
# The baseDomain has to be set up by hand in route53 before installing this chart.
#
# The esDomain entry will be created and linked to the correct ELB.
# The esDomain will not be delete when this chart is uninstalled, you will
# have to delete the route53 by hand if you want to delete it.
#
# NOTE: due to the yaml anchors, these can't be set on the command line
#
baseDomain: &baseDomain "<mydomain>.cluster.cnct.io"
esDomain: &esDomain "es.<mydomain>.cluster.cnct.io"

external-dns:
  aws:
    # These are the credentials for an aws user than can manipulate route53
    # They must be supplied on the command line e.g.:
    # --set external-dns.aws.secretKey="value1",external-dns.aws.accessKey="value2". 
    #
    # If these are invalid, the public DN for elasticsearch will not be created
    secretKey: SET_ON_COMMAND_LINE
    accessKey: SET_ON_COMMAND_LINE
    roleArn: ""
    region: "us-west-2"
    # Filter for zones of this type (optional, options: public, private)
    zoneType: ""
  domainFilters: [ *baseDomain ]  
  rbac:
    create: true

# ======================================
# setup for ElasticSearch
#
image: docker.elastic.co/elasticsearch/elasticsearch-platinum:6.2.4
name: elasticsearch

cluster_name: elasticsearch-cluster
network_host: 0.0.0.0

#Testing (just needs curl, bats)
test:
  image: quay.io/samsung_cnct/e2etester:prod
  account: elastic
  #password: is read from the secret set for the chart

#Services
services:
  es:
    name: elasticsearch
    port: 9200
    port_name: http
    # public: false then no type and nodeport: none
    public: true
    # public: true then type is used.  set annotation for public DNS also
    type: LoadBalancer
    annotations:
      # This annotation is what tells external-dns to create and link the ELB to the FQDN
    - key: external-dns.alpha.kubernetes.io/hostname
      value: *esDomain
  discovery:
    service_name: elasticsearch-discovery
    cluster_port: 9300
    cluster_port_name: cluster-comms
    app_selector: elasticsearch-data

security:
  # This sets the initial password for ElasticSearch user 'elastic'
  # This should be passed in on the command line:  --set security.password=mynewpassord
  password: changeme

data_envs:
  HTTP_ENABLE: "true"
  NODE_DATA: "true"
  NODE_MASTER: "false"
  HTTP_CORS_ENABLE: "false"
  HTTP_CORS_ALLOW_ORIGIN: ""
  MEMORY_LOCK: "false"
  
master_envs: 
  HTTP_ENABLE: "false"
  NODE_DATA: "false"
  NODE_MASTER: "true"
  HTTP_CORS_ENABLE: "false"
  HTTP_CORS_ALLOW_ORIGIN: ""
  MEMORY_LOCK: "false"

#Master StatefulSet
#
# Need a storage class for CI testing
master_create_storage_class: false
#
master_name: elasticsearch-master
# master_replicas: if changing this value, please also update the
# elasticsearch configuration file quorum settings in the
# samsung_cnct/elasticsearch image. This value should not be altered
# when running in production
master_replicas: 3
master_imagePullPolicy: Always
master_cpu_limits: 500m
master_cpu_requests: 500m
master_memory_limits: 4Gi
master_memory_requests: 4Gi
# master_volume_storage: set to small so when exploring with this the
# user doesn't accidentally create very large disks
master_volume_storage: 20Gi
# Xms & Xmx: must be the same
# should be ~75% of total memory allocation
master_Xms_Xmx: 3g
master_tolerations:
 # - key: taintKey
 #   value: taintValue
 #   operator: Equal
 #   effect: NoSchedule
master_scheduling:
  affinity:
    node:
      type: #requiredDuringSchedulingIgnoredDuringExecution
      labels:
      # - key: iamalabelkey
      #   operator: In
      #   values: ["value1", "value2"]
# Peristent Valume Setup
# Data mount point
master_data_mount: "/usr/elasticsearch/data"
#   Note the value must match the name of a pre-created Storage Class
master_storage_class_key: "volume.beta.kubernetes.io/storage-class"
master_storage_class_value: "anything"

#Cluster StatefulSet
# Need a storage class for CI testing
data_create_storage_class: false
#
data_name: elasticsearch-data
# data_replicas: This can be changed at will for scaling purposes
# either in this chart or at the command line during production
data_replicas: 3
# resource notes:  datanodes are pretty heavy.
# These should be modified up for a real production setting
# recommendation is two cores and 20GB of memory for the containers
data_cpu_limits: 500m
data_memory_limits: 4Gi
data_cpu_requests: 500m
data_memory_requests: 4Gi
data_volume_storage: 20Gi
# Xms & Xmx: must be the same
# should be ~75% of total memory allocation
data_Xms_Xmx: 3g
data_tolerations:
 # - key: taintKey
 #   value: taintValue
 #   operator: Equal
 #   effect: NoSchedule
data_scheduling:
  affinity:
    node:
      type: #requiredDuringSchedulingIgnoredDuringExecution
      labels:
      # - key: iamalabelkey
      #   operator: In
      #   values: ["value1", "value2"]

#  if you want to be able to write data to this cluster from 
#  outside the cluster, set the ingress.host value
#ingress:
#  host: elasticsearch.ingest.company.org
#
# Data mount point
data_data_mount: "/usr/elasticsearch/data"
# Peristent Valume Setup
#   Note the value must match the name of a pre-created Storage Class
data_storage_class_key: "volume.beta.kubernetes.io/storage-class"
data_storage_class_value: "anything"
