apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "name" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ template "namewithversion" . }}
    release: "{{.Release.Name}}"
    heritage: "{{.Release.Service}}"
{{- if .Values.config }}
{{- $root := . }}
{{- range $key, $val := .Values.config }}
  {{ $key }}: |-
{{ $val | indent 4}}
{{- end }}
{{ else }}
  elasticsearch.yml: |-
    {{- include "elasticsearch.yml.tpl" . | indent 4}}
{{ end }}
  jvm.options: |-
    {{- include "jvm.options.tpl" . | indent 4}}
  elasticsearch.yml: |-
    {{- include "log4j2.properties.tpl" . | indent 4}}
