{{- if .Values.data_create_storage_class }}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ .Values.data_storage_class_value }}
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
{{- end }}
